Added more debug info to the SVN message when the submission fails.
Included more information to the SVN message when the submitter fails to understand why TestInterleavedSubmissions doesn't cover the scenario in which two participants interleave their submissions.

As the following exception implies, the test doesn't submit the data correctly because it tries to use the same working copy for the submissions of both participants.

org.tmatesoft.svn.core.SVNException: svn: '.../junit-workspace/.metadata/.plugins/edu.illinois.codingspectator.data' is already a working copy for a different URL
at org.tmatesoft.svn.core.internal.wc.SVNErrorManager.error(SVNErrorManager.java:64)
at org.tmatesoft.svn.core.internal.wc.SVNErrorManager.error(SVNErrorManager.java:51)
at org.tmatesoft.svn.core.wc.SVNUpdateClient.doCheckout(SVNUpdateClient.java:937)
at edu.illinois.codingspectator.monitor.core.submission.RemoteSVNManager.doCheckout(RemoteSVNManager.java:56)
at edu.illinois.codingspectator.monitor.core.submission.SVNManager.doCheckout(SVNManager.java:40)
at edu.illinois.codingspectator.monitor.ui.submission.Submitter.doSVNSubmit(Submitter.java:141)
at edu.illinois.codingspectator.monitor.ui .submission.Submitter.submit(Submitter.java:111)
at edu.illinois.codingspectator.monitor.tests.TestInterleavedSubmissions.submit(TestInterleavedSubmissions.java:37)
at edu.illinois.codingspectator.monitor.tests.TestInterleavedSubmissions.submissionsShouldBeEfficientWhenInterleaved(TestInterleavedSubmissions.java:31)

This commit belongs to issue #333.