Resolves the assertion failure of IntroduceFactoryTests.
This commit relates to issue #100
(https://github.com/vazexqi/CodingSpectator/issues/100). In particular, it fixes
the following error.

    org.eclipse.jdt.ui.tests.refactoring.IntroduceFactoryTests
testFactoryClash(org.eclipse.jdt.ui.tests.refactoring.IntroduceFactoryTests)
junit.framework.AssertionFailedError: precondition was supposed to fail at
junit.framework.Assert.fail(Assert.java:47) ...

Generally speaking, checking conditions of refactorings have side effects and
thus they are not idempotent operations.

We intercept the refactoring descriptor during the test and check that it isn't
null. However, we sometimes need to check the initial conditions of the
refactoring before creating its descriptor. On the other hand, the above test
fails when the initial condition is checked more than once.  Therefore, we need
to make sure that we check each kind of condition only once.

This commit redesigns
org.eclipse.jdt.ui.tests.refactoring.RefactoringTest.performRefactoring(Refactoring,
boolean) and
org.eclipse.jdt.ui.tests.refactoring.codingspectator.RefactoringChecker.checkRefactoringDescriptorCreation(Refactoring)
to communicate better. Specifically, checkRefactoringDescriptorCreation now
tells performRefactoring what conditions it has checked and what conditions
remain to be checked by performRefactoring, i.e. none, initial, final, all.
Then, performRefactoring picks up where checkRefactoringDescriptorCreation has
left and checks the remaining conditions.

Because CheckConditionsOperation requires the style not to be NONE, I had to
handle the NONE case manually in performRefactoring. This exceptional behavior
has made the logic of performRefactoring complicated because updating the status
has become more involved and executions of the change operation have had to be
guarded by the well being of the status.